### ISSUE TITLE
read_ctrl.cpp seems to be missing?

### ISSUE THREAD

**Issue by jleppert** [janblumenkamp/robomaster_sdk_can#1]
From CMakeLists.txt:

add_executable(read_ctrl read_ctrl.cpp inc/can_streambuf.hpp inc/protocol.hpp inc/crc.hpp inc/chassis.hpp)

**Comment by janblumenkamp** [comment]
Thanks for noticing and sorry for getting back to you so late! This file was not intended to be part of this repository, I removed it now from the CMakeLists.
